# docker-compose.yml
version: "3.8"
services:
  musicbot:
    build: .
    container_name: discord-musicbot
    env_file: 
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./music_cache:/usr/src/app/music_cache   # stockage local des MP3 / caches
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
